package rol;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josec
 */
public class Rolinterface extends javax.swing.JFrame {
    
    /**
     * Creates new form Interfaz
     */
    
    public Rolinterface() {
              
        initComponents();

        tirada_ataque_panel.setVisible(false);// TODO add your handling code here:
        tirada_critico_panel.setVisible(false);
        
        this.setLocationRelativeTo(null);
        
        
        
        critico_button.setVisible(false);


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        salir_button = new javax.swing.JButton();
        tirada_ataque_button = new javax.swing.JButton();
        tirada_ataque_button1 = new javax.swing.JButton();
        tirada_ataque_button2 = new javax.swing.JButton();
        tirada_ataque_button3 = new javax.swing.JButton();
        tirada_ataque_panel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        texto_dado = new javax.swing.JTextField();
        texto_bonificador = new javax.swing.JTextField();
        texto_enemigo = new javax.swing.JTextField();
        texto_extra = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        texto_resultado = new javax.swing.JLabel();
        texto_critico = new javax.swing.JLabel();
        tirar_dado = new javax.swing.JButton();
        tipo_arma = new javax.swing.JComboBox<>();
        critico_button = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        tirada_critico_panel = new javax.swing.JPanel();
        cerrar_criticos_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        texto_dado1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        texto_resultado1 = new javax.swing.JLabel();
        texto_critico1 = new javax.swing.JLabel();
        tirar_dado1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tipo_critico = new javax.swing.JComboBox<>();
        texto_explicacion_critico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Señor de los Anillos");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(316, 385));
        setMinimumSize(new java.awt.Dimension(316, 385));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panel_principal.setPreferredSize(new java.awt.Dimension(800, 600));

        salir_button.setText("Salir");
        salir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_buttonActionPerformed(evt);
            }
        });

        tirada_ataque_button.setText("Tirada de ataque");
        tirada_ataque_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirada_ataque_buttonActionPerformed(evt);
            }
        });

        tirada_ataque_button1.setText("b");
        tirada_ataque_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirada_ataque_button1ActionPerformed(evt);
            }
        });

        tirada_ataque_button2.setText("c");
        tirada_ataque_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirada_ataque_button2ActionPerformed(evt);
            }
        });

        tirada_ataque_button3.setText("a");
        tirada_ataque_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirada_ataque_button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tirada_ataque_button3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tirada_ataque_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tirada_ataque_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tirada_ataque_button, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_principalLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tirada_ataque_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(tirada_ataque_button3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(tirada_ataque_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(tirada_ataque_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(salir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        tirada_ataque_panel.setPreferredSize(new java.awt.Dimension(800, 600));
        tirada_ataque_panel.setRequestFocusEnabled(false);

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Bonificador defensiva enemigo");

        jLabel2.setText("Extra");

        jLabel3.setText("Bonificador de personaje");

        jLabel4.setText("Tirada de dado");

        texto_dado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_dadoActionPerformed(evt);
            }
        });

        texto_bonificador.setToolTipText("");
        texto_bonificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_bonificadorActionPerformed(evt);
            }
        });

        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        texto_resultado.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        texto_resultado.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(texto_resultado)
                .addGap(38, 38, 38))
        );

        texto_critico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        texto_critico.setForeground(new java.awt.Color(204, 0, 0));
        texto_critico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texto_criticoMouseClicked(evt);
            }
        });

        tirar_dado.setForeground(new java.awt.Color(204, 255, 204));
        tirar_dado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirar_dadoActionPerformed(evt);
            }
        });

        tipo_arma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De filo", "Contundentes", "A dos manos", "Proyectiles", "Armas de asta", "Arrojadizas" }));

        critico_button.setText("Ir a criticos");
        critico_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                critico_buttonActionPerformed(evt);
            }
        });

        jTextField1.setText("Jugador");

        javax.swing.GroupLayout tirada_ataque_panelLayout = new javax.swing.GroupLayout(tirada_ataque_panel);
        tirada_ataque_panel.setLayout(tirada_ataque_panelLayout);
        tirada_ataque_panelLayout.setHorizontalGroup(
            tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                                .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texto_extra, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                    .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texto_enemigo))
                                    .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texto_bonificador)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipo_arma, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(critico_button)
                                    .addComponent(texto_critico, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                                .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(tirada_ataque_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texto_dado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(42, 42, 42)
                                .addComponent(tirar_dado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))
                        .addGap(150, 150, 150)))
                .addContainerGap())
        );
        tirada_ataque_panelLayout.setVerticalGroup(
            tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tirada_ataque_panelLayout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tirada_ataque_panelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(texto_critico, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(critico_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tirada_ataque_panelLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_dado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tirar_dado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_bonificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo_arma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_enemigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tirada_ataque_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_extra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        tirada_critico_panel.setPreferredSize(new java.awt.Dimension(800, 600));
        tirada_critico_panel.setRequestFocusEnabled(false);

        cerrar_criticos_button.setText("Cancelar");
        cerrar_criticos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar_criticos_buttonActionPerformed(evt);
            }
        });

        jLabel8.setText("Tirada de critico");

        texto_dado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_dado1ActionPerformed(evt);
            }
        });

        jButton6.setText("Aceptar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        texto_resultado1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        texto_resultado1.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(texto_resultado1)
                .addGap(39, 39, 39))
        );

        texto_critico1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        texto_critico1.setForeground(new java.awt.Color(204, 0, 0));

        tirar_dado1.setForeground(new java.awt.Color(204, 255, 204));
        tirar_dado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirar_dado1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo de critico");

        tipo_critico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T", "A", "B", "C", "D", "E" }));

        texto_explicacion_critico.setEditable(false);
        texto_explicacion_critico.setColumns(10);
        texto_explicacion_critico.setLineWrap(true);
        texto_explicacion_critico.setRows(5);
        texto_explicacion_critico.setTabSize(5);

        javax.swing.GroupLayout tirada_critico_panelLayout = new javax.swing.GroupLayout(tirada_critico_panel);
        tirada_critico_panel.setLayout(tirada_critico_panelLayout);
        tirada_critico_panelLayout.setHorizontalGroup(
            tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                .addGroup(tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(cerrar_criticos_button, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                        .addGroup(tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipo_critico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(texto_dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(texto_explicacion_critico, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(texto_critico1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                            .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(tirar_dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        tirada_critico_panelLayout.setVerticalGroup(
            tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tirada_critico_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tirada_critico_panelLayout.createSequentialGroup()
                        .addGroup(tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_dado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tirar_dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tirada_critico_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo_critico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texto_explicacion_critico, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tirada_critico_panelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(texto_critico1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cerrar_criticos_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tirada_ataque_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tirada_critico_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tirada_ataque_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tirada_critico_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("LiveScore");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_buttonActionPerformed
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_salir_buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      tirada_ataque_panel.setVisible(false);// TODO add your handling code here:
      panel_principal.setVisible(true);// TODO add your handling code here: // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tirada_ataque_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirada_ataque_buttonActionPerformed
      tirada_ataque_panel.setVisible(true);// TODO add your handling code here:
      panel_principal.setVisible(false);// TODO add your handling code here:

       // TODO add your handling code here:
    }//GEN-LAST:event_tirada_ataque_buttonActionPerformed

    private void texto_dadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_dadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_dadoActionPerformed

    private void texto_bonificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_bonificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_bonificadorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        float dado=0, enemigo=0, bonificador=0, extra=0, resultado=0;   

        if(texto_dado.getText().length()== 0)
        {
            texto_critico.setText("¡Tira el dado!");
            
        }
        else
        {
        
            if(texto_enemigo.getText().length() > 0)
            {
                enemigo= Float.parseFloat(texto_enemigo.getText());
            }
            else if(texto_bonificador.getText().length()>0)
            {
                bonificador= Float.parseFloat(texto_bonificador.getText());

            }
            else if(texto_extra.getText().length()>0)
            {
                extra= Float.parseFloat(texto_extra.getText());

            }
            else
            {
                enemigo=0;
                bonificador=0;
                extra=0;
            }

            dado= Float.parseFloat(texto_dado.getText());

            resultado=dado+bonificador+extra-enemigo;
            String res_aux =Float.toString(resultado);

            texto_resultado.setText(res_aux);

           if(dado < 5)
           {
                texto_critico.setText("PIFIA...");
                critico_button.setVisible(true);
                critico_button.setText("Ir a pifias");
           }

           else if(resultado > 95)
            {
                texto_critico.setText("CRITICO!!");
                critico_button.setVisible(true);
                String arma=String.valueOf(tipo_arma.getSelectedItem());

                if(arma== "De filo")
                {
                    Tabla_interface_defilo tablas=new Tabla_interface_defilo();
                    tablas.setVisible(true);
                }
                else if(arma== "Contundentes")
                {
                    Tabla_interface_contundentes tablas=new Tabla_interface_contundentes();
                    tablas.setVisible(true);
                }
            }
           else{

            
                String arma=String.valueOf(tipo_arma.getSelectedItem());
                if(arma== "De filo")
                {
                    Tabla_interface_defilo tablas=new Tabla_interface_defilo();
                    tablas.setVisible(true);
                }
                else if(arma== "Contundentes")
                {
                    Tabla_interface_contundentes tablas=new Tabla_interface_contundentes();
                    tablas.setVisible(true);
                }
                texto_critico.setText("");
                critico_button.setVisible(false);
            }

            texto_dado.setText("");
            texto_enemigo.setText("");
            texto_bonificador.setText("");
            texto_extra.setText("");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tirar_dadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirar_dadoActionPerformed
        // TODO add your handling code here:
        int numero = (int)(Math.random()*101);
        texto_dado.setText(String.valueOf(numero));
    }//GEN-LAST:event_tirar_dadoActionPerformed

    private void cerrar_criticos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar_criticos_buttonActionPerformed
        texto_explicacion_critico.setText("");
        texto_resultado1.setText("0");
        texto_dado1.setText("");
        tirada_critico_panel.setVisible(false);
        tirada_ataque_panel.setVisible(true);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_cerrar_criticos_buttonActionPerformed

    private void texto_dado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_dado1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_texto_dado1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       float dado= Float.parseFloat(texto_dado1.getText()); 
       texto_explicacion_critico.setText("");
       if(tipo_critico.getSelectedItem()=="T")
           dado-=50;
       else if(tipo_critico.getSelectedItem()=="A")
           dado-=20;
       else if(tipo_critico.getSelectedItem()=="B")
           dado-=10;
       else if(tipo_critico.getSelectedItem()=="D")
           dado+=10;
       else if(tipo_critico.getSelectedItem()=="E")
           dado+=20;
       
       String res_aux =Float.toString(dado);

       texto_resultado1.setText(res_aux);
       
       String arma=String.valueOf(tipo_arma.getSelectedItem());
       
       if(arma=="De filo")
           if(-49<dado && dado<=5)
              texto_explicacion_critico.setText("Un golpe débil que no produce daño extra. +0");
           else if(6<=dado && dado<=20)
               texto_explicacion_critico.setText("Herida leve en la pantorrila. 1pv por asalto");
           else if(21<=dado && dado<=35)
                texto_explicacion_critico.setText("Golpe en la parte superior de la pierna. -5pv. Si no se llevan grebas, 2 puntos de  vida más por asalto");
           else if(36<=dado && dado<=50)
                texto_explicacion_critico.setText("Herida leve en el pecho. -3 pv. y 1pv. por asalto.-5 a la actividad.");       
           else if(51<=dado && dado<=65)
                texto_explicacion_critico.setText("Herida leve en el antebrazo. -4pv. 2pv más por asalto.");                 
           else if(66<=dado && dado<=79)
                texto_explicacion_critico.setText("Aturdido durante un asalto. Herida menos grave en el muslo. -6pv. 1pv por asalto.");              
            else if(81<=dado && dado<=86)
                texto_explicacion_critico.setText("Tajo en los músculos y tendones del brazo que esgrime el arma. El brazo queda inutilizado -10pv y 1pv más por cada asalto.");
            else if(87<=dado && dado<=89)
                     texto_explicacion_critico.setText("Un ojo queda destruido. -10pv. Aturdido durante 30 asaltos.");
            else if(91<=dado && dado<=96)
                     texto_explicacion_critico.setText("Inconsciente durante 6 horas debido a un tajo en el lado de la cabeza. -15pv. Si no se lleva yelmo, muerte instantánea.");
            else if(97<=dado && dado<=99)
                     texto_explicacion_critico.setText("Extremo inferior de la pierna seccionado. -20pv por asalto. Cae y se desmaya.");
            else if(101<=dado && dado<=106)
                     texto_explicacion_critico.setText("Grave herida en el abdomen. -10pv. Pierde 8pv más cada asalto. -10 a la actividad. Aturdido durante 4 asaltos.");
            else if(107<=dado && dado<=109)
                     texto_explicacion_critico.setText("El brazo que esgrimía el arma queda cercenado -15pv por asalto. Cae insconciente inmediatamente.");
            else if(111<=dado && dado<=116)
                     texto_explicacion_critico.setText("Mano cercenada. 12 pv por asalto. Cae al suelo y queda aturdido durante 6 asaltos.");
            else if(117<=dado && dado<=119)
                     texto_explicacion_critico.setText("Tajo en la espina dorsal. Colapso inmediato. Paralizado desde el cuello para abajo permanentemente. -20pv adicionales.");
            else if(dado==80)
                     texto_explicacion_critico.setText("-10 a la actividad. Aturdido durante 2 asaltos. Un golpe en el cuello secciona la arteria carótida. Cuello roto. Muerte tras 1 asalto de intensa agonía.");
            else if(dado==90)
                     texto_explicacion_critico.setText("Destripado, muere instantáneamente. 25% de probabilidad de que tu arma se quede atascada en el contrincante durante 2 asaltos.");
            else if(dado==100)
                     texto_explicacion_critico.setText("Tajo abierto en el costado. Cae inconsciente y muere en 3 asaltos debido a daños masivos en los órganos internos.");
            else if(dado==110)
                     texto_explicacion_critico.setText("Empalado en el corazón. Muere instantáneamente, el corazón destrozado. 25% de probabilidad de que el arma se quede atascada en el enemigo durante 3 turnos");
            else if(dado==120)
                     texto_explicacion_critico.setText("Un tajo en la cabeza destruye el cerebro, lo que hace difícil que el pobre infeliz siga con vida. Expira 'en un suspiro' ");
       
       

       // TODO add your handling code here: 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tirar_dado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirar_dado1ActionPerformed
        int numero = (int)(Math.random()*101);
        texto_dado1.setText(String.valueOf(numero));        // TODO add your handling code here:
    }//GEN-LAST:event_tirar_dado1ActionPerformed

    private void texto_criticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_texto_criticoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_criticoMouseClicked

    private void critico_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_critico_buttonActionPerformed
        tirada_critico_panel.setVisible(true);
        tirada_ataque_panel.setVisible(false);

    }//GEN-LAST:event_critico_buttonActionPerformed

    private void tirada_ataque_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirada_ataque_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tirada_ataque_button1ActionPerformed

    private void tirada_ataque_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirada_ataque_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tirada_ataque_button2ActionPerformed

    private void tirada_ataque_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirada_ataque_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tirada_ataque_button3ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rolinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rolinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rolinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rolinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rolinterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar_criticos_button;
    private javax.swing.JButton critico_button;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JButton salir_button;
    private javax.swing.JTextField texto_bonificador;
    private javax.swing.JLabel texto_critico;
    private javax.swing.JLabel texto_critico1;
    private javax.swing.JTextField texto_dado;
    private javax.swing.JTextField texto_dado1;
    private javax.swing.JTextField texto_enemigo;
    private javax.swing.JTextArea texto_explicacion_critico;
    private javax.swing.JTextField texto_extra;
    private javax.swing.JLabel texto_resultado;
    private javax.swing.JLabel texto_resultado1;
    private javax.swing.JComboBox<String> tipo_arma;
    private javax.swing.JComboBox<String> tipo_critico;
    private javax.swing.JButton tirada_ataque_button;
    private javax.swing.JButton tirada_ataque_button1;
    private javax.swing.JButton tirada_ataque_button2;
    private javax.swing.JButton tirada_ataque_button3;
    private javax.swing.JPanel tirada_ataque_panel;
    private javax.swing.JPanel tirada_critico_panel;
    private javax.swing.JButton tirar_dado;
    private javax.swing.JButton tirar_dado1;
    // End of variables declaration//GEN-END:variables
}
