/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rol;

/**
 *
 * @author jomac
 */
public class Tabla_interface_defilo extends javax.swing.JFrame {

    /**
     * Creates new form Tablas_interface
     */
    public Tabla_interface_defilo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deFilo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_defilo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de ataque con armas de filo");
        setPreferredSize(new java.awt.Dimension(450, 520));
        setResizable(false);

        tabla_defilo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-08", "------", "Posible", "pifia", "-------", "-------"},
                {"09-35", "0", "0", "0", "0", "0"},
                {"36-40", "0", "0", "0", "0", "0"},
                {"41-45", "0", "0", "0", "0", "0"},
                {"46-50", "1", "0", "0", "0", "0"},
                {"51-55", "1", "1", "0", "0", "0"},
                {"56-60", "2", "1", "0", "0", "0"},
                {"61-65", "2", "2", "0", "0", "0"},
                {"66-70", "3", "3", "2", "3", "0"},
                {"71-75", "3", "4", "3", "5", "0"},
                {"76-80", "4", "5", "5", "7A", "7"},
                {"81-85", "5", "6", "6", "9A", "9A"},
                {"86-90", "5", "7", "7A", "10B", "10A"},
                {"91-95", "6", "8", "9A", "12B", "11B"},
                {"96-100", "6", "9", "10B", "13B", "13C"},
                {"101-105", "7", "10A", "11B", "14C", "15C"},
                {"106-110", "8", "11A", "12B", "15C", "17D"},
                {"111-115", "8A", "12B", "13C", "17C", "19D"},
                {"116-120", "9A", "13B", "15C", "18D", "20D"},
                {"121-125", "9A", "13C", "16C", "19D", "21E"},
                {"126-130", "10B", "14C", "17D", "20D", "23E"},
                {"131-135", "11B", "15C", "18D", "22D", "25E"},
                {"136-140", "11C", "16D", "20D", "23E", "27E"},
                {"141-145", "12D", "17D", "21E", "24E", "28E"},
                {"146-150", "12E", "18E", "22E", "25E", "30E"}
            },
            new String [] {
                "Tirada", "Coraza", "C. de malla", "Cuero end.", "Cuero", "Sin armad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_defilo);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deFiloLayout = new javax.swing.GroupLayout(deFilo);
        deFilo.setLayout(deFiloLayout);
        deFiloLayout.setHorizontalGroup(
            deFiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deFiloLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 389, Short.MAX_VALUE))
            .addGroup(deFiloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deFiloLayout.setVerticalGroup(
            deFiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deFiloLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deFilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deFilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla_interface_defilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla_interface_defilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla_interface_defilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla_interface_defilo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla_interface_defilo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel deFilo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_defilo;
    // End of variables declaration//GEN-END:variables
}
