/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rol;

/**
 *
 * @author jomac
 */
public class Tabla_interface_a2manos extends javax.swing.JFrame {

    /**
     * Creates new form Tabla_interface_a2manos
     */
    public Tabla_interface_a2manos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_defilo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 520));
        setResizable(false);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla_defilo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabla_defilo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01-08", "------", "Posible", "pifia", "-------", "-------"},
                {"09-55", "0", "0", "0", "0", "0"},
                {"56-60", "2", "0", "0", "0", "0"},
                {"61-65", "3", "0", "0", "0", "0"},
                {"71-75", "5", "5", "2", "8A", "0"},
                {"76-80", "6", "7", "4A", "10A", "0"},
                {"81-85", "7", "9", "7A", "13B", "10A"},
                {"86-90", "8", "11", "9B", "15B", "13B"},
                {"91-95", "9", "12A", "12B", "17C", "16C"},
                {"96-100", "11", "14A", "14C", "20C", "19D"},
                {"101-105", "12A", "16B", "17C", "22C", "22D"},
                {"106-110", "13A", "18B", "19C", "24C", "25D"},
                {"111-115", "14B", "20C", "22C", "27D", "28E"},
                {"116-120", "15B", "22C", "24D", "29D", "31E"},
                {"121-125", "16C", "24C", "27D", "31D", "33E"},
                {"126-130", "17C", "26D", "29D", "33E", "36E"},
                {"131-135", "19D", "28D", "32E", "36E", "39E"},
                {"136-140", "20D", "29E", "34E", "38E", "42E"},
                {"141-145", "21E", "31E", "37E", "40E", "45E"},
                {"146-150", "22E", "33E", "40E", "43E", "48E"}
            },
            new String [] {
                "Tirada", "Coraza", "C. de malla", "Cuero end.", "Cuero", "Sin armad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_defilo.setCellSelectionEnabled(true);
        tabla_defilo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tabla_defilo.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(tabla_defilo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addContainerGap(336, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(8, 8, 8))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla_interface_a2manos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla_interface_a2manos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla_interface_a2manos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla_interface_a2manos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla_interface_a2manos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_defilo;
    // End of variables declaration//GEN-END:variables
}
